services:
  api:
    image: gegedesembri/telegram-bot-api:latest
    restart: always
    environment:
      TELEGRAM_API_ID: "<TELEGRAM_API_ID>" # replace with your actual API ID
      TELEGRAM_API_HASH: "<TELEGRAM_API_HASH>" # replace with your actual API Hash
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    expose:
      - "8081"  # internal only

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"  # only nginx exposed externally
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  bot:
    image: gegedesembri/vpnpanel:latest
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - ./config.json:/app/config.json
    command: --config=./config.json

volumes:
  telegram-bot-api-data:
