log:
  level: info # LOG LEVEL: error, warn, info, http, verbose, debug, silly
  dir: ./data/log # Directory to store log files

telegram:
  whitelabel: "@GegeVPS" # To display the whitelabel name in the main menu
  channels: # Fitur masih dalam pengembangan, tidak digunakan saat ini
    - "@gegevps_autoscript" # Channel yang harus diikuti oleh client sebelum bisa mengakses bot
    # Tambahkan lebih dari satu channel jika diperlukan, pisahkan dengan koma
  admin_ids: # Daftar Master Admin dengan akses penuh untuk mengelola bot dan co-admin
    - 124324324 # Ganti dengan ID Telegram Anda
    - 124123214 # Bisa lebih dari satu ID, pisahkan dengan koma
    - 123456789 # Contoh ID admin lainnya
  bot:
    token: <BOT_TOKEN> # Ganti dengan token bot Telegram Anda
    api:
      protocol: http
      host: nginx
      port: 80
  botnotif:
    token: <BOTNOTIF_TOKEN> # Ganti dengan token bot notifikasi Telegram Anda
    api:
      protocol: http
      host: nginx
      port: 80
